// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmSimSvrUnity.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dmSimSvrUnity_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_dmSimSvrUnity_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_dmSimSvrUnity_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dmSimSvrUnity_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_dmSimSvrUnity_2eproto;
namespace dm {
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
class DeviceRegistration;
struct DeviceRegistrationDefaultTypeInternal;
extern DeviceRegistrationDefaultTypeInternal _DeviceRegistration_default_instance_;
class DeviceState;
struct DeviceStateDefaultTypeInternal;
extern DeviceStateDefaultTypeInternal _DeviceState_default_instance_;
class InstrumentFlag;
struct InstrumentFlagDefaultTypeInternal;
extern InstrumentFlagDefaultTypeInternal _InstrumentFlag_default_instance_;
class InstrumentMsg;
struct InstrumentMsgDefaultTypeInternal;
extern InstrumentMsgDefaultTypeInternal _InstrumentMsg_default_instance_;
class RightCfg;
struct RightCfgDefaultTypeInternal;
extern RightCfgDefaultTypeInternal _RightCfg_default_instance_;
class Vec3;
struct Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
class Vec4;
struct Vec4DefaultTypeInternal;
extern Vec4DefaultTypeInternal _Vec4_default_instance_;
}  // namespace dm
PROTOBUF_NAMESPACE_OPEN
template <>
::dm::Config* Arena::CreateMaybeMessage<::dm::Config>(Arena*);
template <>
::dm::DeviceRegistration* Arena::CreateMaybeMessage<::dm::DeviceRegistration>(Arena*);
template <>
::dm::DeviceState* Arena::CreateMaybeMessage<::dm::DeviceState>(Arena*);
template <>
::dm::InstrumentFlag* Arena::CreateMaybeMessage<::dm::InstrumentFlag>(Arena*);
template <>
::dm::InstrumentMsg* Arena::CreateMaybeMessage<::dm::InstrumentMsg>(Arena*);
template <>
::dm::RightCfg* Arena::CreateMaybeMessage<::dm::RightCfg>(Arena*);
template <>
::dm::Vec3* Arena::CreateMaybeMessage<::dm::Vec3>(Arena*);
template <>
::dm::Vec4* Arena::CreateMaybeMessage<::dm::Vec4>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace dm {
enum SYSTEM_MENU : int {
  SYS_UNKNOW = 0,
  SYS_STOP = 1,
  SYS_START = 2,
  SYS_SHUTDOWN = 3,
  SYS_RESTART = 4,
  SYSTEM_MENU_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SYSTEM_MENU_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SYSTEM_MENU_IsValid(int value);
constexpr SYSTEM_MENU SYSTEM_MENU_MIN = static_cast<SYSTEM_MENU>(0);
constexpr SYSTEM_MENU SYSTEM_MENU_MAX = static_cast<SYSTEM_MENU>(4);
constexpr int SYSTEM_MENU_ARRAYSIZE = 4 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
SYSTEM_MENU_descriptor();
template <typename T>
const std::string& SYSTEM_MENU_Name(T value) {
  static_assert(std::is_same<T, SYSTEM_MENU>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SYSTEM_MENU_Name().");
  return SYSTEM_MENU_Name(static_cast<SYSTEM_MENU>(value));
}
template <>
inline const std::string& SYSTEM_MENU_Name(SYSTEM_MENU value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<SYSTEM_MENU_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool SYSTEM_MENU_Parse(absl::string_view name, SYSTEM_MENU* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SYSTEM_MENU>(
      SYSTEM_MENU_descriptor(), name, value);
}
enum REGISTRATION_PTTYPE : int {
  TYPE_UNKONE = 0,
  TYPE_LUMBAR = 1,
  TYPE_THORACIC = 2,
  TYPE_CERVICAL = 3,
  REGISTRATION_PTTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  REGISTRATION_PTTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool REGISTRATION_PTTYPE_IsValid(int value);
constexpr REGISTRATION_PTTYPE REGISTRATION_PTTYPE_MIN = static_cast<REGISTRATION_PTTYPE>(0);
constexpr REGISTRATION_PTTYPE REGISTRATION_PTTYPE_MAX = static_cast<REGISTRATION_PTTYPE>(3);
constexpr int REGISTRATION_PTTYPE_ARRAYSIZE = 3 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
REGISTRATION_PTTYPE_descriptor();
template <typename T>
const std::string& REGISTRATION_PTTYPE_Name(T value) {
  static_assert(std::is_same<T, REGISTRATION_PTTYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to REGISTRATION_PTTYPE_Name().");
  return REGISTRATION_PTTYPE_Name(static_cast<REGISTRATION_PTTYPE>(value));
}
template <>
inline const std::string& REGISTRATION_PTTYPE_Name(REGISTRATION_PTTYPE value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<REGISTRATION_PTTYPE_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool REGISTRATION_PTTYPE_Parse(absl::string_view name, REGISTRATION_PTTYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<REGISTRATION_PTTYPE>(
      REGISTRATION_PTTYPE_descriptor(), name, value);
}
enum INSTRUMENT_PACK : int {
  PACK_UNKNOW = 0,
  PACK_PETD = 1,
  PACK_UBE = 2,
  INSTRUMENT_PACK_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  INSTRUMENT_PACK_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool INSTRUMENT_PACK_IsValid(int value);
constexpr INSTRUMENT_PACK INSTRUMENT_PACK_MIN = static_cast<INSTRUMENT_PACK>(0);
constexpr INSTRUMENT_PACK INSTRUMENT_PACK_MAX = static_cast<INSTRUMENT_PACK>(2);
constexpr int INSTRUMENT_PACK_ARRAYSIZE = 2 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
INSTRUMENT_PACK_descriptor();
template <typename T>
const std::string& INSTRUMENT_PACK_Name(T value) {
  static_assert(std::is_same<T, INSTRUMENT_PACK>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to INSTRUMENT_PACK_Name().");
  return INSTRUMENT_PACK_Name(static_cast<INSTRUMENT_PACK>(value));
}
template <>
inline const std::string& INSTRUMENT_PACK_Name(INSTRUMENT_PACK value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<INSTRUMENT_PACK_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool INSTRUMENT_PACK_Parse(absl::string_view name, INSTRUMENT_PACK* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<INSTRUMENT_PACK>(
      INSTRUMENT_PACK_descriptor(), name, value);
}
enum DEVICE : int {
  DEV_UNKNOW = 0,
  DEV_OPT = 1,
  DEV_MAG = 2,
  DEV_FORCE = 3,
  DEV_BONE = 4,
  DEVICE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DEVICE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DEVICE_IsValid(int value);
constexpr DEVICE DEVICE_MIN = static_cast<DEVICE>(0);
constexpr DEVICE DEVICE_MAX = static_cast<DEVICE>(4);
constexpr int DEVICE_ARRAYSIZE = 4 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
DEVICE_descriptor();
template <typename T>
const std::string& DEVICE_Name(T value) {
  static_assert(std::is_same<T, DEVICE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DEVICE_Name().");
  return DEVICE_Name(static_cast<DEVICE>(value));
}
template <>
inline const std::string& DEVICE_Name(DEVICE value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<DEVICE_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool DEVICE_Parse(absl::string_view name, DEVICE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DEVICE>(
      DEVICE_descriptor(), name, value);
}
enum DEV_STATE : int {
  STATE_UNKNOW = 0,
  STATE_OK = 1,
  STATE_ERR = 2,
  DEV_STATE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DEV_STATE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DEV_STATE_IsValid(int value);
constexpr DEV_STATE DEV_STATE_MIN = static_cast<DEV_STATE>(0);
constexpr DEV_STATE DEV_STATE_MAX = static_cast<DEV_STATE>(2);
constexpr int DEV_STATE_ARRAYSIZE = 2 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
DEV_STATE_descriptor();
template <typename T>
const std::string& DEV_STATE_Name(T value) {
  static_assert(std::is_same<T, DEV_STATE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DEV_STATE_Name().");
  return DEV_STATE_Name(static_cast<DEV_STATE>(value));
}
template <>
inline const std::string& DEV_STATE_Name(DEV_STATE value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<DEV_STATE_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool DEV_STATE_Parse(absl::string_view name, DEV_STATE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DEV_STATE>(
      DEV_STATE_descriptor(), name, value);
}
enum REG_ACTION : int {
  REG_UNKNOW = 0,
  REG_CLEAR = 1,
  REG_REGISTER = 2,
  REG_PTS = 3,
  REG_ACTION_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  REG_ACTION_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool REG_ACTION_IsValid(int value);
constexpr REG_ACTION REG_ACTION_MIN = static_cast<REG_ACTION>(0);
constexpr REG_ACTION REG_ACTION_MAX = static_cast<REG_ACTION>(3);
constexpr int REG_ACTION_ARRAYSIZE = 3 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
REG_ACTION_descriptor();
template <typename T>
const std::string& REG_ACTION_Name(T value) {
  static_assert(std::is_same<T, REG_ACTION>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to REG_ACTION_Name().");
  return REG_ACTION_Name(static_cast<REG_ACTION>(value));
}
template <>
inline const std::string& REG_ACTION_Name(REG_ACTION value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<REG_ACTION_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool REG_ACTION_Parse(absl::string_view name, REG_ACTION* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<REG_ACTION>(
      REG_ACTION_descriptor(), name, value);
}
enum INS_FLAG : int {
  FLAG_UNKNOW = 0,
  FLAG_BEGIN = 1,
  FLAG_END = 2,
  INS_FLAG_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  INS_FLAG_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool INS_FLAG_IsValid(int value);
constexpr INS_FLAG INS_FLAG_MIN = static_cast<INS_FLAG>(0);
constexpr INS_FLAG INS_FLAG_MAX = static_cast<INS_FLAG>(2);
constexpr int INS_FLAG_ARRAYSIZE = 2 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
INS_FLAG_descriptor();
template <typename T>
const std::string& INS_FLAG_Name(T value) {
  static_assert(std::is_same<T, INS_FLAG>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to INS_FLAG_Name().");
  return INS_FLAG_Name(static_cast<INS_FLAG>(value));
}
template <>
inline const std::string& INS_FLAG_Name(INS_FLAG value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<INS_FLAG_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool INS_FLAG_Parse(absl::string_view name, INS_FLAG* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<INS_FLAG>(
      INS_FLAG_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Config final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Config(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Config(const Config& from);
  Config(Config&& from) noexcept
    : Config() {
    *this = ::std::move(from);
  }

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Config& default_instance() {
    return *internal_default_instance();
  }
  static inline const Config* internal_default_instance() {
    return reinterpret_cast<const Config*>(
               &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Config& a, Config& b) {
    a.Swap(&b);
  }
  inline void Swap(Config* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Config>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Config& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Config& from) {
    Config::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Config* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.Config";
  }
  protected:
  explicit Config(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSysmenuFieldNumber = 1,
    kRegptFieldNumber = 2,
    kInspackFieldNumber = 3,
  };
  // optional .dm.SYSTEM_MENU sysmenu = 1;
  bool has_sysmenu() const;
  void clear_sysmenu() ;
  ::dm::SYSTEM_MENU sysmenu() const;
  void set_sysmenu(::dm::SYSTEM_MENU value);

  private:
  ::dm::SYSTEM_MENU _internal_sysmenu() const;
  void _internal_set_sysmenu(::dm::SYSTEM_MENU value);

  public:
  // optional .dm.REGISTRATION_PTTYPE regpt = 2;
  bool has_regpt() const;
  void clear_regpt() ;
  ::dm::REGISTRATION_PTTYPE regpt() const;
  void set_regpt(::dm::REGISTRATION_PTTYPE value);

  private:
  ::dm::REGISTRATION_PTTYPE _internal_regpt() const;
  void _internal_set_regpt(::dm::REGISTRATION_PTTYPE value);

  public:
  // optional .dm.INSTRUMENT_PACK inspack = 3;
  bool has_inspack() const;
  void clear_inspack() ;
  ::dm::INSTRUMENT_PACK inspack() const;
  void set_inspack(::dm::INSTRUMENT_PACK value);

  private:
  ::dm::INSTRUMENT_PACK _internal_inspack() const;
  void _internal_set_inspack(::dm::INSTRUMENT_PACK value);

  public:
  // @@protoc_insertion_point(class_scope:dm.Config)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int sysmenu_;
    int regpt_;
    int inspack_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class Vec3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.Vec3) */ {
 public:
  inline Vec3() : Vec3(nullptr) {}
  ~Vec3() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Vec3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec3(const Vec3& from);
  Vec3(Vec3&& from) noexcept
    : Vec3() {
    *this = ::std::move(from);
  }

  inline Vec3& operator=(const Vec3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3& operator=(Vec3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3* internal_default_instance() {
    return reinterpret_cast<const Vec3*>(
               &_Vec3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Vec3& a, Vec3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vec3& from) {
    Vec3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.Vec3";
  }
  protected:
  explicit Vec3(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:dm.Vec3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class Vec4 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.Vec4) */ {
 public:
  inline Vec4() : Vec4(nullptr) {}
  ~Vec4() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Vec4(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec4(const Vec4& from);
  Vec4(Vec4&& from) noexcept
    : Vec4() {
    *this = ::std::move(from);
  }

  inline Vec4& operator=(const Vec4& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec4& operator=(Vec4&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec4& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec4* internal_default_instance() {
    return reinterpret_cast<const Vec4*>(
               &_Vec4_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Vec4& a, Vec4& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec4* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec4* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec4* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec4>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec4& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vec4& from) {
    Vec4::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec4* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.Vec4";
  }
  protected:
  explicit Vec4(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // float w = 4;
  void clear_w() ;
  float w() const;
  void set_w(float value);

  private:
  float _internal_w() const;
  void _internal_set_w(float value);

  public:
  // @@protoc_insertion_point(class_scope:dm.Vec4)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    float w_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class DeviceState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.DeviceState) */ {
 public:
  inline DeviceState() : DeviceState(nullptr) {}
  ~DeviceState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DeviceState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeviceState(const DeviceState& from);
  DeviceState(DeviceState&& from) noexcept
    : DeviceState() {
    *this = ::std::move(from);
  }

  inline DeviceState& operator=(const DeviceState& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeviceState& operator=(DeviceState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeviceState& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeviceState* internal_default_instance() {
    return reinterpret_cast<const DeviceState*>(
               &_DeviceState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DeviceState& a, DeviceState& b) {
    a.Swap(&b);
  }
  inline void Swap(DeviceState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeviceState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeviceState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeviceState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeviceState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeviceState& from) {
    DeviceState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.DeviceState";
  }
  protected:
  explicit DeviceState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDevFieldNumber = 1,
    kStateFieldNumber = 2,
  };
  // .dm.DEVICE dev = 1;
  void clear_dev() ;
  ::dm::DEVICE dev() const;
  void set_dev(::dm::DEVICE value);

  private:
  ::dm::DEVICE _internal_dev() const;
  void _internal_set_dev(::dm::DEVICE value);

  public:
  // .dm.DEV_STATE state = 2;
  void clear_state() ;
  ::dm::DEV_STATE state() const;
  void set_state(::dm::DEV_STATE value);

  private:
  ::dm::DEV_STATE _internal_state() const;
  void _internal_set_state(::dm::DEV_STATE value);

  public:
  // @@protoc_insertion_point(class_scope:dm.DeviceState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int dev_;
    int state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class DeviceRegistration final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.DeviceRegistration) */ {
 public:
  inline DeviceRegistration() : DeviceRegistration(nullptr) {}
  ~DeviceRegistration() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DeviceRegistration(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeviceRegistration(const DeviceRegistration& from);
  DeviceRegistration(DeviceRegistration&& from) noexcept
    : DeviceRegistration() {
    *this = ::std::move(from);
  }

  inline DeviceRegistration& operator=(const DeviceRegistration& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeviceRegistration& operator=(DeviceRegistration&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeviceRegistration& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeviceRegistration* internal_default_instance() {
    return reinterpret_cast<const DeviceRegistration*>(
               &_DeviceRegistration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(DeviceRegistration& a, DeviceRegistration& b) {
    a.Swap(&b);
  }
  inline void Swap(DeviceRegistration* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeviceRegistration* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeviceRegistration* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeviceRegistration>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeviceRegistration& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeviceRegistration& from) {
    DeviceRegistration::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceRegistration* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.DeviceRegistration";
  }
  protected:
  explicit DeviceRegistration(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDevFieldNumber = 1,
    kActionFieldNumber = 2,
    kSuccessFieldNumber = 3,
    kRmsFieldNumber = 4,
  };
  // .dm.DEVICE dev = 1;
  void clear_dev() ;
  ::dm::DEVICE dev() const;
  void set_dev(::dm::DEVICE value);

  private:
  ::dm::DEVICE _internal_dev() const;
  void _internal_set_dev(::dm::DEVICE value);

  public:
  // .dm.REG_ACTION action = 2;
  void clear_action() ;
  ::dm::REG_ACTION action() const;
  void set_action(::dm::REG_ACTION value);

  private:
  ::dm::REG_ACTION _internal_action() const;
  void _internal_set_action(::dm::REG_ACTION value);

  public:
  // bool success = 3;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // float rms = 4;
  void clear_rms() ;
  float rms() const;
  void set_rms(float value);

  private:
  float _internal_rms() const;
  void _internal_set_rms(float value);

  public:
  // @@protoc_insertion_point(class_scope:dm.DeviceRegistration)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int dev_;
    int action_;
    bool success_;
    float rms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class RightCfg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.RightCfg) */ {
 public:
  inline RightCfg() : RightCfg(nullptr) {}
  ~RightCfg() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR RightCfg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RightCfg(const RightCfg& from);
  RightCfg(RightCfg&& from) noexcept
    : RightCfg() {
    *this = ::std::move(from);
  }

  inline RightCfg& operator=(const RightCfg& from) {
    CopyFrom(from);
    return *this;
  }
  inline RightCfg& operator=(RightCfg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RightCfg& default_instance() {
    return *internal_default_instance();
  }
  static inline const RightCfg* internal_default_instance() {
    return reinterpret_cast<const RightCfg*>(
               &_RightCfg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(RightCfg& a, RightCfg& b) {
    a.Swap(&b);
  }
  inline void Swap(RightCfg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RightCfg* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RightCfg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RightCfg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RightCfg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RightCfg& from) {
    RightCfg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RightCfg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.RightCfg";
  }
  protected:
  explicit RightCfg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPivotFieldNumber = 1,
    kMovezFieldNumber = 2,
  };
  // optional .dm.Vec3 pivot = 1;
  bool has_pivot() const;
  void clear_pivot() ;
  const ::dm::Vec3& pivot() const;
  PROTOBUF_NODISCARD ::dm::Vec3* release_pivot();
  ::dm::Vec3* mutable_pivot();
  void set_allocated_pivot(::dm::Vec3* pivot);
  private:
  const ::dm::Vec3& _internal_pivot() const;
  ::dm::Vec3* _internal_mutable_pivot();
  public:
  void unsafe_arena_set_allocated_pivot(
      ::dm::Vec3* pivot);
  ::dm::Vec3* unsafe_arena_release_pivot();
  // optional .dm.Vec3 movez = 2;
  bool has_movez() const;
  void clear_movez() ;
  const ::dm::Vec3& movez() const;
  PROTOBUF_NODISCARD ::dm::Vec3* release_movez();
  ::dm::Vec3* mutable_movez();
  void set_allocated_movez(::dm::Vec3* movez);
  private:
  const ::dm::Vec3& _internal_movez() const;
  ::dm::Vec3* _internal_mutable_movez();
  public:
  void unsafe_arena_set_allocated_movez(
      ::dm::Vec3* movez);
  ::dm::Vec3* unsafe_arena_release_movez();
  // @@protoc_insertion_point(class_scope:dm.RightCfg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::dm::Vec3* pivot_;
    ::dm::Vec3* movez_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class InstrumentMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.InstrumentMsg) */ {
 public:
  inline InstrumentMsg() : InstrumentMsg(nullptr) {}
  ~InstrumentMsg() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR InstrumentMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstrumentMsg(const InstrumentMsg& from);
  InstrumentMsg(InstrumentMsg&& from) noexcept
    : InstrumentMsg() {
    *this = ::std::move(from);
  }

  inline InstrumentMsg& operator=(const InstrumentMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstrumentMsg& operator=(InstrumentMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstrumentMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstrumentMsg* internal_default_instance() {
    return reinterpret_cast<const InstrumentMsg*>(
               &_InstrumentMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(InstrumentMsg& a, InstrumentMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(InstrumentMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstrumentMsg* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstrumentMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstrumentMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstrumentMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstrumentMsg& from) {
    InstrumentMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstrumentMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.InstrumentMsg";
  }
  protected:
  explicit InstrumentMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInsnameFieldNumber = 3,
    kPosFieldNumber = 5,
    kRotFieldNumber = 6,
    kSensoridFieldNumber = 1,
    kInsidFieldNumber = 2,
    kVisibleFieldNumber = 4,
    kQualityFieldNumber = 7,
    kFrameFieldNumber = 8,
  };
  // string insname = 3;
  void clear_insname() ;
  const std::string& insname() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_insname(Arg_&& arg, Args_... args);
  std::string* mutable_insname();
  PROTOBUF_NODISCARD std::string* release_insname();
  void set_allocated_insname(std::string* ptr);

  private:
  const std::string& _internal_insname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_insname(
      const std::string& value);
  std::string* _internal_mutable_insname();

  public:
  // .dm.Vec3 pos = 5;
  bool has_pos() const;
  void clear_pos() ;
  const ::dm::Vec3& pos() const;
  PROTOBUF_NODISCARD ::dm::Vec3* release_pos();
  ::dm::Vec3* mutable_pos();
  void set_allocated_pos(::dm::Vec3* pos);
  private:
  const ::dm::Vec3& _internal_pos() const;
  ::dm::Vec3* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::dm::Vec3* pos);
  ::dm::Vec3* unsafe_arena_release_pos();
  // .dm.Vec4 rot = 6;
  bool has_rot() const;
  void clear_rot() ;
  const ::dm::Vec4& rot() const;
  PROTOBUF_NODISCARD ::dm::Vec4* release_rot();
  ::dm::Vec4* mutable_rot();
  void set_allocated_rot(::dm::Vec4* rot);
  private:
  const ::dm::Vec4& _internal_rot() const;
  ::dm::Vec4* _internal_mutable_rot();
  public:
  void unsafe_arena_set_allocated_rot(
      ::dm::Vec4* rot);
  ::dm::Vec4* unsafe_arena_release_rot();
  // uint32 sensorid = 1;
  void clear_sensorid() ;
  ::uint32_t sensorid() const;
  void set_sensorid(::uint32_t value);

  private:
  ::uint32_t _internal_sensorid() const;
  void _internal_set_sensorid(::uint32_t value);

  public:
  // uint32 insid = 2;
  void clear_insid() ;
  ::uint32_t insid() const;
  void set_insid(::uint32_t value);

  private:
  ::uint32_t _internal_insid() const;
  void _internal_set_insid(::uint32_t value);

  public:
  // bool visible = 4;
  void clear_visible() ;
  bool visible() const;
  void set_visible(bool value);

  private:
  bool _internal_visible() const;
  void _internal_set_visible(bool value);

  public:
  // float quality = 7;
  void clear_quality() ;
  float quality() const;
  void set_quality(float value);

  private:
  float _internal_quality() const;
  void _internal_set_quality(float value);

  public:
  // float frame = 8;
  void clear_frame() ;
  float frame() const;
  void set_frame(float value);

  private:
  float _internal_frame() const;
  void _internal_set_frame(float value);

  public:
  // @@protoc_insertion_point(class_scope:dm.InstrumentMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr insname_;
    ::dm::Vec3* pos_;
    ::dm::Vec4* rot_;
    ::uint32_t sensorid_;
    ::uint32_t insid_;
    bool visible_;
    float quality_;
    float frame_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};// -------------------------------------------------------------------

class InstrumentFlag final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dm.InstrumentFlag) */ {
 public:
  inline InstrumentFlag() : InstrumentFlag(nullptr) {}
  ~InstrumentFlag() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR InstrumentFlag(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstrumentFlag(const InstrumentFlag& from);
  InstrumentFlag(InstrumentFlag&& from) noexcept
    : InstrumentFlag() {
    *this = ::std::move(from);
  }

  inline InstrumentFlag& operator=(const InstrumentFlag& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstrumentFlag& operator=(InstrumentFlag&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstrumentFlag& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstrumentFlag* internal_default_instance() {
    return reinterpret_cast<const InstrumentFlag*>(
               &_InstrumentFlag_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(InstrumentFlag& a, InstrumentFlag& b) {
    a.Swap(&b);
  }
  inline void Swap(InstrumentFlag* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstrumentFlag* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstrumentFlag* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstrumentFlag>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstrumentFlag& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstrumentFlag& from) {
    InstrumentFlag::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstrumentFlag* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "dm.InstrumentFlag";
  }
  protected:
  explicit InstrumentFlag(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // .dm.INS_FLAG flag = 1;
  void clear_flag() ;
  ::dm::INS_FLAG flag() const;
  void set_flag(::dm::INS_FLAG value);

  private:
  ::dm::INS_FLAG _internal_flag() const;
  void _internal_set_flag(::dm::INS_FLAG value);

  public:
  // @@protoc_insertion_point(class_scope:dm.InstrumentFlag)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int flag_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dmSimSvrUnity_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Config

// optional .dm.SYSTEM_MENU sysmenu = 1;
inline bool Config::has_sysmenu() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Config::clear_sysmenu() {
  _impl_.sysmenu_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::dm::SYSTEM_MENU Config::sysmenu() const {
  // @@protoc_insertion_point(field_get:dm.Config.sysmenu)
  return _internal_sysmenu();
}
inline void Config::set_sysmenu(::dm::SYSTEM_MENU value) {
   _internal_set_sysmenu(value);
  // @@protoc_insertion_point(field_set:dm.Config.sysmenu)
}
inline ::dm::SYSTEM_MENU Config::_internal_sysmenu() const {
  return static_cast<::dm::SYSTEM_MENU>(_impl_.sysmenu_);
}
inline void Config::_internal_set_sysmenu(::dm::SYSTEM_MENU value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sysmenu_ = value;
}

// optional .dm.REGISTRATION_PTTYPE regpt = 2;
inline bool Config::has_regpt() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Config::clear_regpt() {
  _impl_.regpt_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::dm::REGISTRATION_PTTYPE Config::regpt() const {
  // @@protoc_insertion_point(field_get:dm.Config.regpt)
  return _internal_regpt();
}
inline void Config::set_regpt(::dm::REGISTRATION_PTTYPE value) {
   _internal_set_regpt(value);
  // @@protoc_insertion_point(field_set:dm.Config.regpt)
}
inline ::dm::REGISTRATION_PTTYPE Config::_internal_regpt() const {
  return static_cast<::dm::REGISTRATION_PTTYPE>(_impl_.regpt_);
}
inline void Config::_internal_set_regpt(::dm::REGISTRATION_PTTYPE value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.regpt_ = value;
}

// optional .dm.INSTRUMENT_PACK inspack = 3;
inline bool Config::has_inspack() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Config::clear_inspack() {
  _impl_.inspack_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::dm::INSTRUMENT_PACK Config::inspack() const {
  // @@protoc_insertion_point(field_get:dm.Config.inspack)
  return _internal_inspack();
}
inline void Config::set_inspack(::dm::INSTRUMENT_PACK value) {
   _internal_set_inspack(value);
  // @@protoc_insertion_point(field_set:dm.Config.inspack)
}
inline ::dm::INSTRUMENT_PACK Config::_internal_inspack() const {
  return static_cast<::dm::INSTRUMENT_PACK>(_impl_.inspack_);
}
inline void Config::_internal_set_inspack(::dm::INSTRUMENT_PACK value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.inspack_ = value;
}

// -------------------------------------------------------------------

// Vec3

// float x = 1;
inline void Vec3::clear_x() {
  _impl_.x_ = 0;
}
inline float Vec3::x() const {
  // @@protoc_insertion_point(field_get:dm.Vec3.x)
  return _internal_x();
}
inline void Vec3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:dm.Vec3.x)
}
inline float Vec3::_internal_x() const {
  return _impl_.x_;
}
inline void Vec3::_internal_set_x(float value) {
  ;
  _impl_.x_ = value;
}

// float y = 2;
inline void Vec3::clear_y() {
  _impl_.y_ = 0;
}
inline float Vec3::y() const {
  // @@protoc_insertion_point(field_get:dm.Vec3.y)
  return _internal_y();
}
inline void Vec3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:dm.Vec3.y)
}
inline float Vec3::_internal_y() const {
  return _impl_.y_;
}
inline void Vec3::_internal_set_y(float value) {
  ;
  _impl_.y_ = value;
}

// float z = 3;
inline void Vec3::clear_z() {
  _impl_.z_ = 0;
}
inline float Vec3::z() const {
  // @@protoc_insertion_point(field_get:dm.Vec3.z)
  return _internal_z();
}
inline void Vec3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:dm.Vec3.z)
}
inline float Vec3::_internal_z() const {
  return _impl_.z_;
}
inline void Vec3::_internal_set_z(float value) {
  ;
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// Vec4

// float x = 1;
inline void Vec4::clear_x() {
  _impl_.x_ = 0;
}
inline float Vec4::x() const {
  // @@protoc_insertion_point(field_get:dm.Vec4.x)
  return _internal_x();
}
inline void Vec4::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:dm.Vec4.x)
}
inline float Vec4::_internal_x() const {
  return _impl_.x_;
}
inline void Vec4::_internal_set_x(float value) {
  ;
  _impl_.x_ = value;
}

// float y = 2;
inline void Vec4::clear_y() {
  _impl_.y_ = 0;
}
inline float Vec4::y() const {
  // @@protoc_insertion_point(field_get:dm.Vec4.y)
  return _internal_y();
}
inline void Vec4::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:dm.Vec4.y)
}
inline float Vec4::_internal_y() const {
  return _impl_.y_;
}
inline void Vec4::_internal_set_y(float value) {
  ;
  _impl_.y_ = value;
}

// float z = 3;
inline void Vec4::clear_z() {
  _impl_.z_ = 0;
}
inline float Vec4::z() const {
  // @@protoc_insertion_point(field_get:dm.Vec4.z)
  return _internal_z();
}
inline void Vec4::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:dm.Vec4.z)
}
inline float Vec4::_internal_z() const {
  return _impl_.z_;
}
inline void Vec4::_internal_set_z(float value) {
  ;
  _impl_.z_ = value;
}

// float w = 4;
inline void Vec4::clear_w() {
  _impl_.w_ = 0;
}
inline float Vec4::w() const {
  // @@protoc_insertion_point(field_get:dm.Vec4.w)
  return _internal_w();
}
inline void Vec4::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:dm.Vec4.w)
}
inline float Vec4::_internal_w() const {
  return _impl_.w_;
}
inline void Vec4::_internal_set_w(float value) {
  ;
  _impl_.w_ = value;
}

// -------------------------------------------------------------------

// DeviceState

// .dm.DEVICE dev = 1;
inline void DeviceState::clear_dev() {
  _impl_.dev_ = 0;
}
inline ::dm::DEVICE DeviceState::dev() const {
  // @@protoc_insertion_point(field_get:dm.DeviceState.dev)
  return _internal_dev();
}
inline void DeviceState::set_dev(::dm::DEVICE value) {
   _internal_set_dev(value);
  // @@protoc_insertion_point(field_set:dm.DeviceState.dev)
}
inline ::dm::DEVICE DeviceState::_internal_dev() const {
  return static_cast<::dm::DEVICE>(_impl_.dev_);
}
inline void DeviceState::_internal_set_dev(::dm::DEVICE value) {
  ;
  _impl_.dev_ = value;
}

// .dm.DEV_STATE state = 2;
inline void DeviceState::clear_state() {
  _impl_.state_ = 0;
}
inline ::dm::DEV_STATE DeviceState::state() const {
  // @@protoc_insertion_point(field_get:dm.DeviceState.state)
  return _internal_state();
}
inline void DeviceState::set_state(::dm::DEV_STATE value) {
   _internal_set_state(value);
  // @@protoc_insertion_point(field_set:dm.DeviceState.state)
}
inline ::dm::DEV_STATE DeviceState::_internal_state() const {
  return static_cast<::dm::DEV_STATE>(_impl_.state_);
}
inline void DeviceState::_internal_set_state(::dm::DEV_STATE value) {
  ;
  _impl_.state_ = value;
}

// -------------------------------------------------------------------

// DeviceRegistration

// .dm.DEVICE dev = 1;
inline void DeviceRegistration::clear_dev() {
  _impl_.dev_ = 0;
}
inline ::dm::DEVICE DeviceRegistration::dev() const {
  // @@protoc_insertion_point(field_get:dm.DeviceRegistration.dev)
  return _internal_dev();
}
inline void DeviceRegistration::set_dev(::dm::DEVICE value) {
   _internal_set_dev(value);
  // @@protoc_insertion_point(field_set:dm.DeviceRegistration.dev)
}
inline ::dm::DEVICE DeviceRegistration::_internal_dev() const {
  return static_cast<::dm::DEVICE>(_impl_.dev_);
}
inline void DeviceRegistration::_internal_set_dev(::dm::DEVICE value) {
  ;
  _impl_.dev_ = value;
}

// .dm.REG_ACTION action = 2;
inline void DeviceRegistration::clear_action() {
  _impl_.action_ = 0;
}
inline ::dm::REG_ACTION DeviceRegistration::action() const {
  // @@protoc_insertion_point(field_get:dm.DeviceRegistration.action)
  return _internal_action();
}
inline void DeviceRegistration::set_action(::dm::REG_ACTION value) {
   _internal_set_action(value);
  // @@protoc_insertion_point(field_set:dm.DeviceRegistration.action)
}
inline ::dm::REG_ACTION DeviceRegistration::_internal_action() const {
  return static_cast<::dm::REG_ACTION>(_impl_.action_);
}
inline void DeviceRegistration::_internal_set_action(::dm::REG_ACTION value) {
  ;
  _impl_.action_ = value;
}

// bool success = 3;
inline void DeviceRegistration::clear_success() {
  _impl_.success_ = false;
}
inline bool DeviceRegistration::success() const {
  // @@protoc_insertion_point(field_get:dm.DeviceRegistration.success)
  return _internal_success();
}
inline void DeviceRegistration::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:dm.DeviceRegistration.success)
}
inline bool DeviceRegistration::_internal_success() const {
  return _impl_.success_;
}
inline void DeviceRegistration::_internal_set_success(bool value) {
  ;
  _impl_.success_ = value;
}

// float rms = 4;
inline void DeviceRegistration::clear_rms() {
  _impl_.rms_ = 0;
}
inline float DeviceRegistration::rms() const {
  // @@protoc_insertion_point(field_get:dm.DeviceRegistration.rms)
  return _internal_rms();
}
inline void DeviceRegistration::set_rms(float value) {
  _internal_set_rms(value);
  // @@protoc_insertion_point(field_set:dm.DeviceRegistration.rms)
}
inline float DeviceRegistration::_internal_rms() const {
  return _impl_.rms_;
}
inline void DeviceRegistration::_internal_set_rms(float value) {
  ;
  _impl_.rms_ = value;
}

// -------------------------------------------------------------------

// RightCfg

// optional .dm.Vec3 pivot = 1;
inline bool RightCfg::has_pivot() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pivot_ != nullptr);
  return value;
}
inline void RightCfg::clear_pivot() {
  if (_impl_.pivot_ != nullptr) _impl_.pivot_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::dm::Vec3& RightCfg::_internal_pivot() const {
  const ::dm::Vec3* p = _impl_.pivot_;
  return p != nullptr ? *p : reinterpret_cast<const ::dm::Vec3&>(
      ::dm::_Vec3_default_instance_);
}
inline const ::dm::Vec3& RightCfg::pivot() const {
  // @@protoc_insertion_point(field_get:dm.RightCfg.pivot)
  return _internal_pivot();
}
inline void RightCfg::unsafe_arena_set_allocated_pivot(
    ::dm::Vec3* pivot) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pivot_);
  }
  _impl_.pivot_ = pivot;
  if (pivot) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dm.RightCfg.pivot)
}
inline ::dm::Vec3* RightCfg::release_pivot() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dm::Vec3* temp = _impl_.pivot_;
  _impl_.pivot_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dm::Vec3* RightCfg::unsafe_arena_release_pivot() {
  // @@protoc_insertion_point(field_release:dm.RightCfg.pivot)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dm::Vec3* temp = _impl_.pivot_;
  _impl_.pivot_ = nullptr;
  return temp;
}
inline ::dm::Vec3* RightCfg::_internal_mutable_pivot() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.pivot_ == nullptr) {
    auto* p = CreateMaybeMessage<::dm::Vec3>(GetArenaForAllocation());
    _impl_.pivot_ = p;
  }
  return _impl_.pivot_;
}
inline ::dm::Vec3* RightCfg::mutable_pivot() {
  ::dm::Vec3* _msg = _internal_mutable_pivot();
  // @@protoc_insertion_point(field_mutable:dm.RightCfg.pivot)
  return _msg;
}
inline void RightCfg::set_allocated_pivot(::dm::Vec3* pivot) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pivot_;
  }
  if (pivot) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pivot);
    if (message_arena != submessage_arena) {
      pivot = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pivot, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pivot_ = pivot;
  // @@protoc_insertion_point(field_set_allocated:dm.RightCfg.pivot)
}

// optional .dm.Vec3 movez = 2;
inline bool RightCfg::has_movez() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.movez_ != nullptr);
  return value;
}
inline void RightCfg::clear_movez() {
  if (_impl_.movez_ != nullptr) _impl_.movez_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::dm::Vec3& RightCfg::_internal_movez() const {
  const ::dm::Vec3* p = _impl_.movez_;
  return p != nullptr ? *p : reinterpret_cast<const ::dm::Vec3&>(
      ::dm::_Vec3_default_instance_);
}
inline const ::dm::Vec3& RightCfg::movez() const {
  // @@protoc_insertion_point(field_get:dm.RightCfg.movez)
  return _internal_movez();
}
inline void RightCfg::unsafe_arena_set_allocated_movez(
    ::dm::Vec3* movez) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.movez_);
  }
  _impl_.movez_ = movez;
  if (movez) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dm.RightCfg.movez)
}
inline ::dm::Vec3* RightCfg::release_movez() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dm::Vec3* temp = _impl_.movez_;
  _impl_.movez_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dm::Vec3* RightCfg::unsafe_arena_release_movez() {
  // @@protoc_insertion_point(field_release:dm.RightCfg.movez)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dm::Vec3* temp = _impl_.movez_;
  _impl_.movez_ = nullptr;
  return temp;
}
inline ::dm::Vec3* RightCfg::_internal_mutable_movez() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.movez_ == nullptr) {
    auto* p = CreateMaybeMessage<::dm::Vec3>(GetArenaForAllocation());
    _impl_.movez_ = p;
  }
  return _impl_.movez_;
}
inline ::dm::Vec3* RightCfg::mutable_movez() {
  ::dm::Vec3* _msg = _internal_mutable_movez();
  // @@protoc_insertion_point(field_mutable:dm.RightCfg.movez)
  return _msg;
}
inline void RightCfg::set_allocated_movez(::dm::Vec3* movez) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.movez_;
  }
  if (movez) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(movez);
    if (message_arena != submessage_arena) {
      movez = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, movez, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.movez_ = movez;
  // @@protoc_insertion_point(field_set_allocated:dm.RightCfg.movez)
}

// -------------------------------------------------------------------

// InstrumentMsg

// uint32 sensorid = 1;
inline void InstrumentMsg::clear_sensorid() {
  _impl_.sensorid_ = 0u;
}
inline ::uint32_t InstrumentMsg::sensorid() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.sensorid)
  return _internal_sensorid();
}
inline void InstrumentMsg::set_sensorid(::uint32_t value) {
  _internal_set_sensorid(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.sensorid)
}
inline ::uint32_t InstrumentMsg::_internal_sensorid() const {
  return _impl_.sensorid_;
}
inline void InstrumentMsg::_internal_set_sensorid(::uint32_t value) {
  ;
  _impl_.sensorid_ = value;
}

// uint32 insid = 2;
inline void InstrumentMsg::clear_insid() {
  _impl_.insid_ = 0u;
}
inline ::uint32_t InstrumentMsg::insid() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.insid)
  return _internal_insid();
}
inline void InstrumentMsg::set_insid(::uint32_t value) {
  _internal_set_insid(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.insid)
}
inline ::uint32_t InstrumentMsg::_internal_insid() const {
  return _impl_.insid_;
}
inline void InstrumentMsg::_internal_set_insid(::uint32_t value) {
  ;
  _impl_.insid_ = value;
}

// string insname = 3;
inline void InstrumentMsg::clear_insname() {
  _impl_.insname_.ClearToEmpty();
}
inline const std::string& InstrumentMsg::insname() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.insname)
  return _internal_insname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InstrumentMsg::set_insname(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.insname_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.insname)
}
inline std::string* InstrumentMsg::mutable_insname() {
  std::string* _s = _internal_mutable_insname();
  // @@protoc_insertion_point(field_mutable:dm.InstrumentMsg.insname)
  return _s;
}
inline const std::string& InstrumentMsg::_internal_insname() const {
  return _impl_.insname_.Get();
}
inline void InstrumentMsg::_internal_set_insname(const std::string& value) {
  ;


  _impl_.insname_.Set(value, GetArenaForAllocation());
}
inline std::string* InstrumentMsg::_internal_mutable_insname() {
  ;
  return _impl_.insname_.Mutable( GetArenaForAllocation());
}
inline std::string* InstrumentMsg::release_insname() {
  // @@protoc_insertion_point(field_release:dm.InstrumentMsg.insname)
  return _impl_.insname_.Release();
}
inline void InstrumentMsg::set_allocated_insname(std::string* value) {
  _impl_.insname_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.insname_.IsDefault()) {
          _impl_.insname_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dm.InstrumentMsg.insname)
}

// bool visible = 4;
inline void InstrumentMsg::clear_visible() {
  _impl_.visible_ = false;
}
inline bool InstrumentMsg::visible() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.visible)
  return _internal_visible();
}
inline void InstrumentMsg::set_visible(bool value) {
  _internal_set_visible(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.visible)
}
inline bool InstrumentMsg::_internal_visible() const {
  return _impl_.visible_;
}
inline void InstrumentMsg::_internal_set_visible(bool value) {
  ;
  _impl_.visible_ = value;
}

// .dm.Vec3 pos = 5;
inline bool InstrumentMsg::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline void InstrumentMsg::clear_pos() {
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::dm::Vec3& InstrumentMsg::_internal_pos() const {
  const ::dm::Vec3* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::dm::Vec3&>(
      ::dm::_Vec3_default_instance_);
}
inline const ::dm::Vec3& InstrumentMsg::pos() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.pos)
  return _internal_pos();
}
inline void InstrumentMsg::unsafe_arena_set_allocated_pos(
    ::dm::Vec3* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dm.InstrumentMsg.pos)
}
inline ::dm::Vec3* InstrumentMsg::release_pos() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dm::Vec3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dm::Vec3* InstrumentMsg::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:dm.InstrumentMsg.pos)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dm::Vec3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::dm::Vec3* InstrumentMsg::_internal_mutable_pos() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::dm::Vec3>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::dm::Vec3* InstrumentMsg::mutable_pos() {
  ::dm::Vec3* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:dm.InstrumentMsg.pos)
  return _msg;
}
inline void InstrumentMsg::set_allocated_pos(::dm::Vec3* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:dm.InstrumentMsg.pos)
}

// .dm.Vec4 rot = 6;
inline bool InstrumentMsg::has_rot() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rot_ != nullptr);
  return value;
}
inline void InstrumentMsg::clear_rot() {
  if (_impl_.rot_ != nullptr) _impl_.rot_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::dm::Vec4& InstrumentMsg::_internal_rot() const {
  const ::dm::Vec4* p = _impl_.rot_;
  return p != nullptr ? *p : reinterpret_cast<const ::dm::Vec4&>(
      ::dm::_Vec4_default_instance_);
}
inline const ::dm::Vec4& InstrumentMsg::rot() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.rot)
  return _internal_rot();
}
inline void InstrumentMsg::unsafe_arena_set_allocated_rot(
    ::dm::Vec4* rot) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rot_);
  }
  _impl_.rot_ = rot;
  if (rot) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dm.InstrumentMsg.rot)
}
inline ::dm::Vec4* InstrumentMsg::release_rot() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dm::Vec4* temp = _impl_.rot_;
  _impl_.rot_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dm::Vec4* InstrumentMsg::unsafe_arena_release_rot() {
  // @@protoc_insertion_point(field_release:dm.InstrumentMsg.rot)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::dm::Vec4* temp = _impl_.rot_;
  _impl_.rot_ = nullptr;
  return temp;
}
inline ::dm::Vec4* InstrumentMsg::_internal_mutable_rot() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.rot_ == nullptr) {
    auto* p = CreateMaybeMessage<::dm::Vec4>(GetArenaForAllocation());
    _impl_.rot_ = p;
  }
  return _impl_.rot_;
}
inline ::dm::Vec4* InstrumentMsg::mutable_rot() {
  ::dm::Vec4* _msg = _internal_mutable_rot();
  // @@protoc_insertion_point(field_mutable:dm.InstrumentMsg.rot)
  return _msg;
}
inline void InstrumentMsg::set_allocated_rot(::dm::Vec4* rot) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.rot_;
  }
  if (rot) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(rot);
    if (message_arena != submessage_arena) {
      rot = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rot, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.rot_ = rot;
  // @@protoc_insertion_point(field_set_allocated:dm.InstrumentMsg.rot)
}

// float quality = 7;
inline void InstrumentMsg::clear_quality() {
  _impl_.quality_ = 0;
}
inline float InstrumentMsg::quality() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.quality)
  return _internal_quality();
}
inline void InstrumentMsg::set_quality(float value) {
  _internal_set_quality(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.quality)
}
inline float InstrumentMsg::_internal_quality() const {
  return _impl_.quality_;
}
inline void InstrumentMsg::_internal_set_quality(float value) {
  ;
  _impl_.quality_ = value;
}

// float frame = 8;
inline void InstrumentMsg::clear_frame() {
  _impl_.frame_ = 0;
}
inline float InstrumentMsg::frame() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentMsg.frame)
  return _internal_frame();
}
inline void InstrumentMsg::set_frame(float value) {
  _internal_set_frame(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentMsg.frame)
}
inline float InstrumentMsg::_internal_frame() const {
  return _impl_.frame_;
}
inline void InstrumentMsg::_internal_set_frame(float value) {
  ;
  _impl_.frame_ = value;
}

// -------------------------------------------------------------------

// InstrumentFlag

// .dm.INS_FLAG flag = 1;
inline void InstrumentFlag::clear_flag() {
  _impl_.flag_ = 0;
}
inline ::dm::INS_FLAG InstrumentFlag::flag() const {
  // @@protoc_insertion_point(field_get:dm.InstrumentFlag.flag)
  return _internal_flag();
}
inline void InstrumentFlag::set_flag(::dm::INS_FLAG value) {
   _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:dm.InstrumentFlag.flag)
}
inline ::dm::INS_FLAG InstrumentFlag::_internal_flag() const {
  return static_cast<::dm::INS_FLAG>(_impl_.flag_);
}
inline void InstrumentFlag::_internal_set_flag(::dm::INS_FLAG value) {
  ;
  _impl_.flag_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dm


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::dm::SYSTEM_MENU> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::SYSTEM_MENU>() {
  return ::dm::SYSTEM_MENU_descriptor();
}
template <>
struct is_proto_enum<::dm::REGISTRATION_PTTYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::REGISTRATION_PTTYPE>() {
  return ::dm::REGISTRATION_PTTYPE_descriptor();
}
template <>
struct is_proto_enum<::dm::INSTRUMENT_PACK> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::INSTRUMENT_PACK>() {
  return ::dm::INSTRUMENT_PACK_descriptor();
}
template <>
struct is_proto_enum<::dm::DEVICE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::DEVICE>() {
  return ::dm::DEVICE_descriptor();
}
template <>
struct is_proto_enum<::dm::DEV_STATE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::DEV_STATE>() {
  return ::dm::DEV_STATE_descriptor();
}
template <>
struct is_proto_enum<::dm::REG_ACTION> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::REG_ACTION>() {
  return ::dm::REG_ACTION_descriptor();
}
template <>
struct is_proto_enum<::dm::INS_FLAG> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::dm::INS_FLAG>() {
  return ::dm::INS_FLAG_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_dmSimSvrUnity_2eproto_2epb_2eh
