// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmSimSvrUnity.proto

#include "dmSimSvrUnity.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace dm {
template <typename>
PROTOBUF_CONSTEXPR Config::Config(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.sysmenu_)*/ 0

  , /*decltype(_impl_.regpt_)*/ 0

  , /*decltype(_impl_.inspack_)*/ 0
} {}
struct ConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigDefaultTypeInternal() {}
  union {
    Config _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigDefaultTypeInternal _Config_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR Vec3::Vec3(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/ 0

  , /*decltype(_impl_.y_)*/ 0

  , /*decltype(_impl_.z_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Vec3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vec3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vec3DefaultTypeInternal() {}
  union {
    Vec3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vec3DefaultTypeInternal _Vec3_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR Vec4::Vec4(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/ 0

  , /*decltype(_impl_.y_)*/ 0

  , /*decltype(_impl_.z_)*/ 0

  , /*decltype(_impl_.w_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Vec4DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vec4DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vec4DefaultTypeInternal() {}
  union {
    Vec4 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vec4DefaultTypeInternal _Vec4_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR DeviceState::DeviceState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dev_)*/ 0

  , /*decltype(_impl_.state_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DeviceStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeviceStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeviceStateDefaultTypeInternal() {}
  union {
    DeviceState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeviceStateDefaultTypeInternal _DeviceState_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR DeviceRegistration::DeviceRegistration(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dev_)*/ 0

  , /*decltype(_impl_.action_)*/ 0

  , /*decltype(_impl_.success_)*/ false

  , /*decltype(_impl_.rms_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DeviceRegistrationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeviceRegistrationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeviceRegistrationDefaultTypeInternal() {}
  union {
    DeviceRegistration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeviceRegistrationDefaultTypeInternal _DeviceRegistration_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR RightCfg::RightCfg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.pivot_)*/nullptr
  , /*decltype(_impl_.movez_)*/nullptr} {}
struct RightCfgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RightCfgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RightCfgDefaultTypeInternal() {}
  union {
    RightCfg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RightCfgDefaultTypeInternal _RightCfg_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR InstrumentMsg::InstrumentMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.insname_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.pos_)*/nullptr
  , /*decltype(_impl_.rot_)*/nullptr
  , /*decltype(_impl_.sensorid_)*/ 0u

  , /*decltype(_impl_.insid_)*/ 0u

  , /*decltype(_impl_.visible_)*/ false

  , /*decltype(_impl_.quality_)*/ 0

  , /*decltype(_impl_.frame_)*/ 0
} {}
struct InstrumentMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstrumentMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstrumentMsgDefaultTypeInternal() {}
  union {
    InstrumentMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstrumentMsgDefaultTypeInternal _InstrumentMsg_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR InstrumentFlag::InstrumentFlag(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.flag_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstrumentFlagDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstrumentFlagDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstrumentFlagDefaultTypeInternal() {}
  union {
    InstrumentFlag _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstrumentFlagDefaultTypeInternal _InstrumentFlag_default_instance_;
}  // namespace dm
static ::_pb::Metadata file_level_metadata_dmSimSvrUnity_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dmSimSvrUnity_2eproto[7];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_dmSimSvrUnity_2eproto = nullptr;
const ::uint32_t TableStruct_dmSimSvrUnity_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::dm::Config, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::dm::Config, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::Config, _impl_.sysmenu_),
    PROTOBUF_FIELD_OFFSET(::dm::Config, _impl_.regpt_),
    PROTOBUF_FIELD_OFFSET(::dm::Config, _impl_.inspack_),
    0,
    1,
    2,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dm::Vec3, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::Vec3, _impl_.x_),
    PROTOBUF_FIELD_OFFSET(::dm::Vec3, _impl_.y_),
    PROTOBUF_FIELD_OFFSET(::dm::Vec3, _impl_.z_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dm::Vec4, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::Vec4, _impl_.x_),
    PROTOBUF_FIELD_OFFSET(::dm::Vec4, _impl_.y_),
    PROTOBUF_FIELD_OFFSET(::dm::Vec4, _impl_.z_),
    PROTOBUF_FIELD_OFFSET(::dm::Vec4, _impl_.w_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dm::DeviceState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::DeviceState, _impl_.dev_),
    PROTOBUF_FIELD_OFFSET(::dm::DeviceState, _impl_.state_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dm::DeviceRegistration, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::DeviceRegistration, _impl_.dev_),
    PROTOBUF_FIELD_OFFSET(::dm::DeviceRegistration, _impl_.action_),
    PROTOBUF_FIELD_OFFSET(::dm::DeviceRegistration, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::dm::DeviceRegistration, _impl_.rms_),
    PROTOBUF_FIELD_OFFSET(::dm::RightCfg, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::dm::RightCfg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::RightCfg, _impl_.pivot_),
    PROTOBUF_FIELD_OFFSET(::dm::RightCfg, _impl_.movez_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.sensorid_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.insid_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.insname_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.visible_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.pos_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.rot_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.quality_),
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentMsg, _impl_.frame_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
    1,
    ~0u,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentFlag, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::dm::InstrumentFlag, _impl_.flag_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 11, -1, sizeof(::dm::Config)},
        { 14, -1, -1, sizeof(::dm::Vec3)},
        { 25, -1, -1, sizeof(::dm::Vec4)},
        { 37, -1, -1, sizeof(::dm::DeviceState)},
        { 47, -1, -1, sizeof(::dm::DeviceRegistration)},
        { 59, 69, -1, sizeof(::dm::RightCfg)},
        { 71, 87, -1, sizeof(::dm::InstrumentMsg)},
        { 95, -1, -1, sizeof(::dm::InstrumentFlag)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::dm::_Config_default_instance_._instance,
    &::dm::_Vec3_default_instance_._instance,
    &::dm::_Vec4_default_instance_._instance,
    &::dm::_DeviceState_default_instance_._instance,
    &::dm::_DeviceRegistration_default_instance_._instance,
    &::dm::_RightCfg_default_instance_._instance,
    &::dm::_InstrumentMsg_default_instance_._instance,
    &::dm::_InstrumentFlag_default_instance_._instance,
};
const char descriptor_table_protodef_dmSimSvrUnity_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\023dmSimSvrUnity.proto\022\002dm\"\251\001\n\006Config\022%\n\007"
    "sysmenu\030\001 \001(\0162\017.dm.SYSTEM_MENUH\000\210\001\001\022+\n\005r"
    "egpt\030\002 \001(\0162\027.dm.REGISTRATION_PTTYPEH\001\210\001\001"
    "\022)\n\007inspack\030\003 \001(\0162\023.dm.INSTRUMENT_PACKH\002"
    "\210\001\001B\n\n\010_sysmenuB\010\n\006_regptB\n\n\010_inspack\"\'\n"
    "\004Vec3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"2"
    "\n\004Vec4\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022"
    "\t\n\001w\030\004 \001(\002\"D\n\013DeviceState\022\027\n\003dev\030\001 \001(\0162\n"
    ".dm.DEVICE\022\034\n\005state\030\002 \001(\0162\r.dm.DEV_STATE"
    "\"k\n\022DeviceRegistration\022\027\n\003dev\030\001 \001(\0162\n.dm"
    ".DEVICE\022\036\n\006action\030\002 \001(\0162\016.dm.REG_ACTION\022"
    "\017\n\007success\030\003 \001(\010\022\013\n\003rms\030\004 \001(\002\"Z\n\010RightCf"
    "g\022\034\n\005pivot\030\001 \001(\0132\010.dm.Vec3H\000\210\001\001\022\034\n\005movez"
    "\030\002 \001(\0132\010.dm.Vec3H\001\210\001\001B\010\n\006_pivotB\010\n\006_move"
    "z\"\240\001\n\rInstrumentMsg\022\020\n\010sensorid\030\001 \001(\r\022\r\n"
    "\005insid\030\002 \001(\r\022\017\n\007insname\030\003 \001(\t\022\017\n\007visible"
    "\030\004 \001(\010\022\025\n\003pos\030\005 \001(\0132\010.dm.Vec3\022\025\n\003rot\030\006 \001"
    "(\0132\010.dm.Vec4\022\017\n\007quality\030\007 \001(\002\022\r\n\005frame\030\010"
    " \001(\002\",\n\016InstrumentFlag\022\032\n\004flag\030\001 \001(\0162\014.d"
    "m.INS_FLAG*]\n\013SYSTEM_MENU\022\016\n\nSYS_UNKNOW\020"
    "\000\022\014\n\010SYS_STOP\020\001\022\r\n\tSYS_START\020\002\022\020\n\014SYS_SH"
    "UTDOWN\020\003\022\017\n\013SYS_RESTART\020\004*]\n\023REGISTRATIO"
    "N_PTTYPE\022\017\n\013TYPE_UNKONE\020\000\022\017\n\013TYPE_LUMBAR"
    "\020\001\022\021\n\rTYPE_THORACIC\020\002\022\021\n\rTYPE_CERVICAL\020\003"
    "*\?\n\017INSTRUMENT_PACK\022\017\n\013PACK_UNKNOW\020\000\022\r\n\t"
    "PACK_PETD\020\001\022\014\n\010PACK_UBE\020\002*O\n\006DEVICE\022\016\n\nD"
    "EV_UNKNOW\020\000\022\013\n\007DEV_OPT\020\001\022\013\n\007DEV_MAG\020\002\022\r\n"
    "\tDEV_FORCE\020\003\022\014\n\010DEV_BONE\020\004*:\n\tDEV_STATE\022"
    "\020\n\014STATE_UNKNOW\020\000\022\014\n\010STATE_OK\020\001\022\r\n\tSTATE"
    "_ERR\020\002*J\n\nREG_ACTION\022\016\n\nREG_UNKNOW\020\000\022\r\n\t"
    "REG_CLEAR\020\001\022\020\n\014REG_REGISTER\020\002\022\013\n\007REG_PTS"
    "\020\003*9\n\010INS_FLAG\022\017\n\013FLAG_UNKNOW\020\000\022\016\n\nFLAG_"
    "BEGIN\020\001\022\014\n\010FLAG_END\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_dmSimSvrUnity_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dmSimSvrUnity_2eproto = {
    false,
    false,
    1309,
    descriptor_table_protodef_dmSimSvrUnity_2eproto,
    "dmSimSvrUnity.proto",
    &descriptor_table_dmSimSvrUnity_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_dmSimSvrUnity_2eproto::offsets,
    file_level_metadata_dmSimSvrUnity_2eproto,
    file_level_enum_descriptors_dmSimSvrUnity_2eproto,
    file_level_service_descriptors_dmSimSvrUnity_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dmSimSvrUnity_2eproto_getter() {
  return &descriptor_table_dmSimSvrUnity_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dmSimSvrUnity_2eproto(&descriptor_table_dmSimSvrUnity_2eproto);
namespace dm {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SYSTEM_MENU_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[0];
}
bool SYSTEM_MENU_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* REGISTRATION_PTTYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[1];
}
bool REGISTRATION_PTTYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* INSTRUMENT_PACK_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[2];
}
bool INSTRUMENT_PACK_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DEVICE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[3];
}
bool DEVICE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DEV_STATE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[4];
}
bool DEV_STATE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* REG_ACTION_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[5];
}
bool REG_ACTION_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* INS_FLAG_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dmSimSvrUnity_2eproto);
  return file_level_enum_descriptors_dmSimSvrUnity_2eproto[6];
}
bool INS_FLAG_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
// ===================================================================

class Config::_Internal {
 public:
  using HasBits = decltype(std::declval<Config>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Config, _impl_._has_bits_);
  static void set_has_sysmenu(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_regpt(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_inspack(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

Config::Config(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.Config)
}
Config::Config(const Config& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.Config)
}

inline void Config::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.sysmenu_) { 0 }

    , decltype(_impl_.regpt_) { 0 }

    , decltype(_impl_.inspack_) { 0 }

  };
}

Config::~Config() {
  // @@protoc_insertion_point(destructor:dm.Config)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Config::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void Config::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Config::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.Config)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.sysmenu_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.inspack_) -
        reinterpret_cast<char*>(&_impl_.sysmenu_)) + sizeof(_impl_.inspack_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Config::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .dm.SYSTEM_MENU sysmenu = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_sysmenu(static_cast<::dm::SYSTEM_MENU>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .dm.REGISTRATION_PTTYPE regpt = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_regpt(static_cast<::dm::REGISTRATION_PTTYPE>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .dm.INSTRUMENT_PACK inspack = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_inspack(static_cast<::dm::INSTRUMENT_PACK>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Config::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.Config)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .dm.SYSTEM_MENU sysmenu = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_sysmenu(), target);
  }

  // optional .dm.REGISTRATION_PTTYPE regpt = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_regpt(), target);
  }

  // optional .dm.INSTRUMENT_PACK inspack = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_inspack(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.Config)
  return target;
}

::size_t Config::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.Config)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .dm.SYSTEM_MENU sysmenu = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_sysmenu());
    }

    // optional .dm.REGISTRATION_PTTYPE regpt = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_regpt());
    }

    // optional .dm.INSTRUMENT_PACK inspack = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_inspack());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Config::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Config::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Config::GetClassData() const { return &_class_data_; }


void Config::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Config*>(&to_msg);
  auto& from = static_cast<const Config&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.Config)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.sysmenu_ = from._impl_.sysmenu_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.regpt_ = from._impl_.regpt_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.inspack_ = from._impl_.inspack_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Config::CopyFrom(const Config& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.Config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Config::IsInitialized() const {
  return true;
}

void Config::InternalSwap(Config* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Config, _impl_.inspack_)
      + sizeof(Config::_impl_.inspack_)
      - PROTOBUF_FIELD_OFFSET(Config, _impl_.sysmenu_)>(
          reinterpret_cast<char*>(&_impl_.sysmenu_),
          reinterpret_cast<char*>(&other->_impl_.sysmenu_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Config::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[0]);
}
// ===================================================================

class Vec3::_Internal {
 public:
};

Vec3::Vec3(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.Vec3)
}
Vec3::Vec3(const Vec3& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.Vec3)
}

inline void Vec3::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.x_) { 0 }

    , decltype(_impl_.y_) { 0 }

    , decltype(_impl_.z_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Vec3::~Vec3() {
  // @@protoc_insertion_point(destructor:dm.Vec3)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Vec3::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void Vec3::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Vec3::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.Vec3)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Vec3::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Vec3::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.Vec3)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.Vec3)
  return target;
}

::size_t Vec3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.Vec3)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 5;
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 5;
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Vec3::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Vec3::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Vec3::GetClassData() const { return &_class_data_; }


void Vec3::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Vec3*>(&to_msg);
  auto& from = static_cast<const Vec3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.Vec3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Vec3::CopyFrom(const Vec3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.Vec3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec3::IsInitialized() const {
  return true;
}

void Vec3::InternalSwap(Vec3* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vec3, _impl_.z_)
      + sizeof(Vec3::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Vec3, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Vec3::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[1]);
}
// ===================================================================

class Vec4::_Internal {
 public:
};

Vec4::Vec4(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.Vec4)
}
Vec4::Vec4(const Vec4& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.Vec4)
}

inline void Vec4::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.x_) { 0 }

    , decltype(_impl_.y_) { 0 }

    , decltype(_impl_.z_) { 0 }

    , decltype(_impl_.w_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Vec4::~Vec4() {
  // @@protoc_insertion_point(destructor:dm.Vec4)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Vec4::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void Vec4::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Vec4::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.Vec4)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.w_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.w_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Vec4::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float w = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 37)) {
          _impl_.w_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Vec4::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.Vec4)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_z(), target);
  }

  // float w = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_w = this->_internal_w();
  ::uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_w(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.Vec4)
  return target;
}

::size_t Vec4::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.Vec4)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 5;
  }

  // float y = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 5;
  }

  // float z = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 5;
  }

  // float w = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_w = this->_internal_w();
  ::uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Vec4::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Vec4::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Vec4::GetClassData() const { return &_class_data_; }


void Vec4::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Vec4*>(&to_msg);
  auto& from = static_cast<const Vec4&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.Vec4)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_w = from._internal_w();
  ::uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    _this->_internal_set_w(from._internal_w());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Vec4::CopyFrom(const Vec4& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.Vec4)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vec4::IsInitialized() const {
  return true;
}

void Vec4::InternalSwap(Vec4* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vec4, _impl_.w_)
      + sizeof(Vec4::_impl_.w_)
      - PROTOBUF_FIELD_OFFSET(Vec4, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Vec4::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[2]);
}
// ===================================================================

class DeviceState::_Internal {
 public:
};

DeviceState::DeviceState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.DeviceState)
}
DeviceState::DeviceState(const DeviceState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.DeviceState)
}

inline void DeviceState::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.dev_) { 0 }

    , decltype(_impl_.state_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DeviceState::~DeviceState() {
  // @@protoc_insertion_point(destructor:dm.DeviceState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DeviceState::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void DeviceState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DeviceState::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.DeviceState)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dev_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.state_) -
      reinterpret_cast<char*>(&_impl_.dev_)) + sizeof(_impl_.state_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeviceState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .dm.DEVICE dev = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_dev(static_cast<::dm::DEVICE>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // .dm.DEV_STATE state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_state(static_cast<::dm::DEV_STATE>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DeviceState::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.DeviceState)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .dm.DEVICE dev = 1;
  if (this->_internal_dev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_dev(), target);
  }

  // .dm.DEV_STATE state = 2;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.DeviceState)
  return target;
}

::size_t DeviceState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.DeviceState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .dm.DEVICE dev = 1;
  if (this->_internal_dev() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_dev());
  }

  // .dm.DEV_STATE state = 2;
  if (this->_internal_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeviceState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DeviceState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeviceState::GetClassData() const { return &_class_data_; }


void DeviceState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DeviceState*>(&to_msg);
  auto& from = static_cast<const DeviceState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.DeviceState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dev() != 0) {
    _this->_internal_set_dev(from._internal_dev());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeviceState::CopyFrom(const DeviceState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.DeviceState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceState::IsInitialized() const {
  return true;
}

void DeviceState::InternalSwap(DeviceState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeviceState, _impl_.state_)
      + sizeof(DeviceState::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(DeviceState, _impl_.dev_)>(
          reinterpret_cast<char*>(&_impl_.dev_),
          reinterpret_cast<char*>(&other->_impl_.dev_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DeviceState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[3]);
}
// ===================================================================

class DeviceRegistration::_Internal {
 public:
};

DeviceRegistration::DeviceRegistration(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.DeviceRegistration)
}
DeviceRegistration::DeviceRegistration(const DeviceRegistration& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.DeviceRegistration)
}

inline void DeviceRegistration::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.dev_) { 0 }

    , decltype(_impl_.action_) { 0 }

    , decltype(_impl_.success_) { false }

    , decltype(_impl_.rms_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DeviceRegistration::~DeviceRegistration() {
  // @@protoc_insertion_point(destructor:dm.DeviceRegistration)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DeviceRegistration::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void DeviceRegistration::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DeviceRegistration::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.DeviceRegistration)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dev_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rms_) -
      reinterpret_cast<char*>(&_impl_.dev_)) + sizeof(_impl_.rms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeviceRegistration::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .dm.DEVICE dev = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_dev(static_cast<::dm::DEVICE>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // .dm.REG_ACTION action = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_action(static_cast<::dm::REG_ACTION>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // bool success = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // float rms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 37)) {
          _impl_.rms_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DeviceRegistration::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.DeviceRegistration)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .dm.DEVICE dev = 1;
  if (this->_internal_dev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_dev(), target);
  }

  // .dm.REG_ACTION action = 2;
  if (this->_internal_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_action(), target);
  }

  // bool success = 3;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_success(), target);
  }

  // float rms = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rms = this->_internal_rms();
  ::uint32_t raw_rms;
  memcpy(&raw_rms, &tmp_rms, sizeof(tmp_rms));
  if (raw_rms != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_rms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.DeviceRegistration)
  return target;
}

::size_t DeviceRegistration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.DeviceRegistration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .dm.DEVICE dev = 1;
  if (this->_internal_dev() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_dev());
  }

  // .dm.REG_ACTION action = 2;
  if (this->_internal_action() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_action());
  }

  // bool success = 3;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  // float rms = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rms = this->_internal_rms();
  ::uint32_t raw_rms;
  memcpy(&raw_rms, &tmp_rms, sizeof(tmp_rms));
  if (raw_rms != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeviceRegistration::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DeviceRegistration::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeviceRegistration::GetClassData() const { return &_class_data_; }


void DeviceRegistration::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DeviceRegistration*>(&to_msg);
  auto& from = static_cast<const DeviceRegistration&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.DeviceRegistration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dev() != 0) {
    _this->_internal_set_dev(from._internal_dev());
  }
  if (from._internal_action() != 0) {
    _this->_internal_set_action(from._internal_action());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rms = from._internal_rms();
  ::uint32_t raw_rms;
  memcpy(&raw_rms, &tmp_rms, sizeof(tmp_rms));
  if (raw_rms != 0) {
    _this->_internal_set_rms(from._internal_rms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeviceRegistration::CopyFrom(const DeviceRegistration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.DeviceRegistration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceRegistration::IsInitialized() const {
  return true;
}

void DeviceRegistration::InternalSwap(DeviceRegistration* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeviceRegistration, _impl_.rms_)
      + sizeof(DeviceRegistration::_impl_.rms_)
      - PROTOBUF_FIELD_OFFSET(DeviceRegistration, _impl_.dev_)>(
          reinterpret_cast<char*>(&_impl_.dev_),
          reinterpret_cast<char*>(&other->_impl_.dev_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DeviceRegistration::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[4]);
}
// ===================================================================

class RightCfg::_Internal {
 public:
  using HasBits = decltype(std::declval<RightCfg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(RightCfg, _impl_._has_bits_);
  static const ::dm::Vec3& pivot(const RightCfg* msg);
  static void set_has_pivot(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::dm::Vec3& movez(const RightCfg* msg);
  static void set_has_movez(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::dm::Vec3&
RightCfg::_Internal::pivot(const RightCfg* msg) {
  return *msg->_impl_.pivot_;
}
const ::dm::Vec3&
RightCfg::_Internal::movez(const RightCfg* msg) {
  return *msg->_impl_.movez_;
}
RightCfg::RightCfg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.RightCfg)
}
RightCfg::RightCfg(const RightCfg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RightCfg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pivot_){nullptr}
    , decltype(_impl_.movez_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.pivot_ = new ::dm::Vec3(*from._impl_.pivot_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.movez_ = new ::dm::Vec3(*from._impl_.movez_);
  }
  // @@protoc_insertion_point(copy_constructor:dm.RightCfg)
}

inline void RightCfg::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.pivot_){nullptr}
    , decltype(_impl_.movez_){nullptr}
  };
}

RightCfg::~RightCfg() {
  // @@protoc_insertion_point(destructor:dm.RightCfg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RightCfg::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.pivot_;
  if (this != internal_default_instance()) delete _impl_.movez_;
}

void RightCfg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RightCfg::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.RightCfg)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.pivot_ != nullptr);
      _impl_.pivot_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.movez_ != nullptr);
      _impl_.movez_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RightCfg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .dm.Vec3 pivot = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_pivot(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .dm.Vec3 movez = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_movez(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* RightCfg::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.RightCfg)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .dm.Vec3 pivot = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::pivot(this),
        _Internal::pivot(this).GetCachedSize(), target, stream);
  }

  // optional .dm.Vec3 movez = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::movez(this),
        _Internal::movez(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.RightCfg)
  return target;
}

::size_t RightCfg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.RightCfg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .dm.Vec3 pivot = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.pivot_);
    }

    // optional .dm.Vec3 movez = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.movez_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RightCfg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RightCfg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RightCfg::GetClassData() const { return &_class_data_; }


void RightCfg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RightCfg*>(&to_msg);
  auto& from = static_cast<const RightCfg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.RightCfg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_pivot()->::dm::Vec3::MergeFrom(
          from._internal_pivot());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_movez()->::dm::Vec3::MergeFrom(
          from._internal_movez());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RightCfg::CopyFrom(const RightCfg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.RightCfg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RightCfg::IsInitialized() const {
  return true;
}

void RightCfg::InternalSwap(RightCfg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RightCfg, _impl_.movez_)
      + sizeof(RightCfg::_impl_.movez_)
      - PROTOBUF_FIELD_OFFSET(RightCfg, _impl_.pivot_)>(
          reinterpret_cast<char*>(&_impl_.pivot_),
          reinterpret_cast<char*>(&other->_impl_.pivot_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RightCfg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[5]);
}
// ===================================================================

class InstrumentMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<InstrumentMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(InstrumentMsg, _impl_._has_bits_);
  static const ::dm::Vec3& pos(const InstrumentMsg* msg);
  static void set_has_pos(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::dm::Vec4& rot(const InstrumentMsg* msg);
  static void set_has_rot(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::dm::Vec3&
InstrumentMsg::_Internal::pos(const InstrumentMsg* msg) {
  return *msg->_impl_.pos_;
}
const ::dm::Vec4&
InstrumentMsg::_Internal::rot(const InstrumentMsg* msg) {
  return *msg->_impl_.rot_;
}
InstrumentMsg::InstrumentMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.InstrumentMsg)
}
InstrumentMsg::InstrumentMsg(const InstrumentMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstrumentMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.insname_) {}

    , decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , decltype(_impl_.sensorid_) {}

    , decltype(_impl_.insid_) {}

    , decltype(_impl_.visible_) {}

    , decltype(_impl_.quality_) {}

    , decltype(_impl_.frame_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.insname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.insname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_insname().empty()) {
    _this->_impl_.insname_.Set(from._internal_insname(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.pos_ = new ::dm::Vec3(*from._impl_.pos_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.rot_ = new ::dm::Vec4(*from._impl_.rot_);
  }
  ::memcpy(&_impl_.sensorid_, &from._impl_.sensorid_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.frame_) -
    reinterpret_cast<char*>(&_impl_.sensorid_)) + sizeof(_impl_.frame_));
  // @@protoc_insertion_point(copy_constructor:dm.InstrumentMsg)
}

inline void InstrumentMsg::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.insname_) {}

    , decltype(_impl_.pos_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , decltype(_impl_.sensorid_) { 0u }

    , decltype(_impl_.insid_) { 0u }

    , decltype(_impl_.visible_) { false }

    , decltype(_impl_.quality_) { 0 }

    , decltype(_impl_.frame_) { 0 }

  };
  _impl_.insname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.insname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InstrumentMsg::~InstrumentMsg() {
  // @@protoc_insertion_point(destructor:dm.InstrumentMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstrumentMsg::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.insname_.Destroy();
  if (this != internal_default_instance()) delete _impl_.pos_;
  if (this != internal_default_instance()) delete _impl_.rot_;
}

void InstrumentMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstrumentMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.InstrumentMsg)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.insname_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.pos_ != nullptr);
      _impl_.pos_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rot_ != nullptr);
      _impl_.rot_->Clear();
    }
  }
  ::memset(&_impl_.sensorid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.frame_) -
      reinterpret_cast<char*>(&_impl_.sensorid_)) + sizeof(_impl_.frame_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstrumentMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 sensorid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _impl_.sensorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // uint32 insid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.insid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string insname = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_insname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dm.InstrumentMsg.insname"));
        } else {
          goto handle_unusual;
        }
        continue;
      // bool visible = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _impl_.visible_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .dm.Vec3 pos = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_pos(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .dm.Vec4 rot = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_rot(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // float quality = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 61)) {
          _impl_.quality_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float frame = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 69)) {
          _impl_.frame_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* InstrumentMsg::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.InstrumentMsg)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 sensorid = 1;
  if (this->_internal_sensorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_sensorid(), target);
  }

  // uint32 insid = 2;
  if (this->_internal_insid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_insid(), target);
  }

  // string insname = 3;
  if (!this->_internal_insname().empty()) {
    const std::string& _s = this->_internal_insname();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "dm.InstrumentMsg.insname");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bool visible = 4;
  if (this->_internal_visible() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_visible(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .dm.Vec3 pos = 5;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::pos(this),
        _Internal::pos(this).GetCachedSize(), target, stream);
  }

  // .dm.Vec4 rot = 6;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::rot(this),
        _Internal::rot(this).GetCachedSize(), target, stream);
  }

  // float quality = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_quality = this->_internal_quality();
  ::uint32_t raw_quality;
  memcpy(&raw_quality, &tmp_quality, sizeof(tmp_quality));
  if (raw_quality != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_quality(), target);
  }

  // float frame = 8;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_frame = this->_internal_frame();
  ::uint32_t raw_frame;
  memcpy(&raw_frame, &tmp_frame, sizeof(tmp_frame));
  if (raw_frame != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this->_internal_frame(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.InstrumentMsg)
  return target;
}

::size_t InstrumentMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.InstrumentMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string insname = 3;
  if (!this->_internal_insname().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_insname());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .dm.Vec3 pos = 5;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.pos_);
    }

    // .dm.Vec4 rot = 6;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.rot_);
    }

  }
  // uint32 sensorid = 1;
  if (this->_internal_sensorid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_sensorid());
  }

  // uint32 insid = 2;
  if (this->_internal_insid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_insid());
  }

  // bool visible = 4;
  if (this->_internal_visible() != 0) {
    total_size += 2;
  }

  // float quality = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_quality = this->_internal_quality();
  ::uint32_t raw_quality;
  memcpy(&raw_quality, &tmp_quality, sizeof(tmp_quality));
  if (raw_quality != 0) {
    total_size += 5;
  }

  // float frame = 8;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_frame = this->_internal_frame();
  ::uint32_t raw_frame;
  memcpy(&raw_frame, &tmp_frame, sizeof(tmp_frame));
  if (raw_frame != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstrumentMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstrumentMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstrumentMsg::GetClassData() const { return &_class_data_; }


void InstrumentMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstrumentMsg*>(&to_msg);
  auto& from = static_cast<const InstrumentMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.InstrumentMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_insname().empty()) {
    _this->_internal_set_insname(from._internal_insname());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_pos()->::dm::Vec3::MergeFrom(
          from._internal_pos());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_rot()->::dm::Vec4::MergeFrom(
          from._internal_rot());
    }
  }
  if (from._internal_sensorid() != 0) {
    _this->_internal_set_sensorid(from._internal_sensorid());
  }
  if (from._internal_insid() != 0) {
    _this->_internal_set_insid(from._internal_insid());
  }
  if (from._internal_visible() != 0) {
    _this->_internal_set_visible(from._internal_visible());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_quality = from._internal_quality();
  ::uint32_t raw_quality;
  memcpy(&raw_quality, &tmp_quality, sizeof(tmp_quality));
  if (raw_quality != 0) {
    _this->_internal_set_quality(from._internal_quality());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_frame = from._internal_frame();
  ::uint32_t raw_frame;
  memcpy(&raw_frame, &tmp_frame, sizeof(tmp_frame));
  if (raw_frame != 0) {
    _this->_internal_set_frame(from._internal_frame());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstrumentMsg::CopyFrom(const InstrumentMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.InstrumentMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstrumentMsg::IsInitialized() const {
  return true;
}

void InstrumentMsg::InternalSwap(InstrumentMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.insname_, lhs_arena,
                                       &other->_impl_.insname_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InstrumentMsg, _impl_.frame_)
      + sizeof(InstrumentMsg::_impl_.frame_)
      - PROTOBUF_FIELD_OFFSET(InstrumentMsg, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InstrumentMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[6]);
}
// ===================================================================

class InstrumentFlag::_Internal {
 public:
};

InstrumentFlag::InstrumentFlag(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dm.InstrumentFlag)
}
InstrumentFlag::InstrumentFlag(const InstrumentFlag& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dm.InstrumentFlag)
}

inline void InstrumentFlag::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.flag_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InstrumentFlag::~InstrumentFlag() {
  // @@protoc_insertion_point(destructor:dm.InstrumentFlag)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstrumentFlag::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void InstrumentFlag::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstrumentFlag::Clear() {
// @@protoc_insertion_point(message_clear_start:dm.InstrumentFlag)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.flag_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstrumentFlag::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .dm.INS_FLAG flag = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_flag(static_cast<::dm::INS_FLAG>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* InstrumentFlag::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dm.InstrumentFlag)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .dm.INS_FLAG flag = 1;
  if (this->_internal_flag() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_flag(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dm.InstrumentFlag)
  return target;
}

::size_t InstrumentFlag::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dm.InstrumentFlag)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .dm.INS_FLAG flag = 1;
  if (this->_internal_flag() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_flag());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstrumentFlag::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstrumentFlag::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstrumentFlag::GetClassData() const { return &_class_data_; }


void InstrumentFlag::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstrumentFlag*>(&to_msg);
  auto& from = static_cast<const InstrumentFlag&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dm.InstrumentFlag)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_flag() != 0) {
    _this->_internal_set_flag(from._internal_flag());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstrumentFlag::CopyFrom(const InstrumentFlag& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dm.InstrumentFlag)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstrumentFlag::IsInitialized() const {
  return true;
}

void InstrumentFlag::InternalSwap(InstrumentFlag* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.flag_, other->_impl_.flag_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InstrumentFlag::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dmSimSvrUnity_2eproto_getter, &descriptor_table_dmSimSvrUnity_2eproto_once,
      file_level_metadata_dmSimSvrUnity_2eproto[7]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace dm
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dm::Config*
Arena::CreateMaybeMessage< ::dm::Config >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::Config >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::Vec3*
Arena::CreateMaybeMessage< ::dm::Vec3 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::Vec3 >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::Vec4*
Arena::CreateMaybeMessage< ::dm::Vec4 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::Vec4 >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::DeviceState*
Arena::CreateMaybeMessage< ::dm::DeviceState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::DeviceState >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::DeviceRegistration*
Arena::CreateMaybeMessage< ::dm::DeviceRegistration >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::DeviceRegistration >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::RightCfg*
Arena::CreateMaybeMessage< ::dm::RightCfg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::RightCfg >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::InstrumentMsg*
Arena::CreateMaybeMessage< ::dm::InstrumentMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::InstrumentMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::dm::InstrumentFlag*
Arena::CreateMaybeMessage< ::dm::InstrumentFlag >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dm::InstrumentFlag >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
